server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://39.101.214.63:3306/applet?serverTimezone=Asia/Shanghai&characterEncoding=utf-8&useSSL=false
    username: root
    password: 991226gsj
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.qq.com
    username: 541099558@qq.com
    password: medeljkrtgucbebd
    port: 587 # 465,587



mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true #驼峰命名
    lazy-loading-enabled: true  #延迟加载
  type-aliases-package: com.applet.bean.entity
  mapper-locations: classpath:/mapper/*Mapper.xml
